Initial commit
EgMeln/thirdProjectJava pull request #1
Opened 2020-09-25 10:14 UTC by EgMeln

2020-09-27 13:13 UTC, VeronikaYastr requested changes

2020-09-27 13:13 UTC, VeronikaYastr commented on src/main/java/com/bsu/by/Main.java
> +        secondStr.setCharAt(0, Character.toUpperCase(str.charAt(0)));
Нужно тогда сделать проверку, что строка не пустая.
Потому что метод charAt кинет исключение (вот его код):
```
if ((index < 0) || (index >= value.length)) {
            throw new StringIndexOutOfBoundsException(index);
        }
```

2020-09-27 13:13 UTC, VeronikaYastr commented on src/main/java/com/bsu/by/Main.java
> +        Scanner in = new Scanner(System.in);
Сканер должен быть в try-catch

2020-09-27 14:57 UTC, EgMeln commented on src/main/java/com/bsu/by/Main.java
> +        secondStr.setCharAt(0, Character.toUpperCase(str.charAt(0)));
Вроде как исправил.

2020-09-27 14:57 UTC, EgMeln commented on src/main/java/com/bsu/by/Main.java
> +        Scanner in = new Scanner(System.in);
Исправил.

2020-09-28 11:11 UTC, VeronikaYastr requested changes

2020-09-28 11:11 UTC, VeronikaYastr commented on src/main/java/com/bsu/by/Main.java
> +                throw new StringIndexOutOfBoundsException("Your line is empty.");
Лучше InvalidParameter / IllegalArgument exception. А то не понятно, причем тут выход за пределы строки, если пользователь просто ввел что-то)

Вообще по условию должна быть не одна строка считана, а циклом построчное считывание текста, пока пользователь не введет пустую строку. Было бы хорошо, если бы ты это добавил.

2020-09-28 15:18 UTC, VeronikaYastr requested changes
Почти😄

2020-09-28 15:18 UTC, VeronikaYastr commented on src/test/java/com/bsu/by/MainTest.java
> +        finishedLine = Main.toLargeLetter(str);
Можно сразу присвоить
List<String> actualStr = Main.toLargeLetter(str);

2020-09-28 15:18 UTC, VeronikaYastr commented on src/main/java/com/bsu/by/Main.java
> +    static void OutList(List<String> text) {
C маленькой буквы должно быть название метода))

2020-09-28 15:18 UTC, VeronikaYastr commented on src/main/java/com/bsu/by/Main.java
> +            StringBuilder secondStr = new StringBuilder(str);
modifiedStr, resultStr - как угодно, но не secondStr, пожалуйста🙃

2020-09-28 15:18 UTC, VeronikaYastr commented on src/main/java/com/bsu/by/Main.java
> +        List<String> text2;
Тоже, что такое text2?)) 

Лучше в этом методе оставить просто вывод списка в консоль, а в мэйне вызвать toLargeLetter и передать в этот метод. А можно просто сделать list.toString вместо этого метода вообще)

2020-09-28 15:37 UTC, EgMeln commented on src/main/java/com/bsu/by/Main.java
> +                throw new StringIndexOutOfBoundsException("Your line is empty.");
Исправил.

2020-09-28 15:37 UTC, VeronikaYastr commented
👍 Можно мержить)

2020-09-28 15:41 UTC, merged